version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: node-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres-db:5432/mydatabase
    env_file: 
      -  ../.env
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ../:/usr/src/app

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}   # Captura do .env ou usa 'postgres' como padrão
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}  # Captura do .env ou usa 'password' como padrão
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}  # Captura do .env ou usa 'mydatabase' como padrão
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
